[workspace]
authors = ["Yuhao Chen <hello@chenyuhao.me>"]
channels = ["conda-forge"]
name = "ChessNGen"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[pypi-dependencies]
chess = ">=1.11.2, <2"
pillow = ">=12.1.0, <13"
pyarrow = ">=23.0.0, <24"
torch = ">=2.10.0, <3"
torchvision = ">=0.25.0, <0.26"
vector-quantize-pytorch = ">=1.27.20, <2"
einops = ">=0.8.2, <0.9"
fastapi = ">=0.115.0, <1"
uvicorn = ">=0.34.0, <1"
aim = ">=3.29, <4"

[system-requirements]
macos = "14.0"

[dependencies]
python = ">=3.12,<3.13"
